
export default {
    Flex: require('mk-mobile-component/lib/components/flex'),
    WingBlank: require('mk-mobile-component/lib/components/wingBlank'),
    WhiteSpace: require('mk-mobile-component/lib/components/whiteSpace'),
    Drawer: require('mk-mobile-component/lib/components/drawer'),
    Menu: require('mk-mobile-component/lib/components/menu'),
    NavBar: require('mk-mobile-component/lib/components/navBar'),
    Popover: require('mk-mobile-component/lib/components/popover'),
    SegmentedControl: require('mk-mobile-component/lib/components/segmentedControl'),
    Tabs: require('mk-mobile-component/lib/components/tabs'),
    TabBar: require('mk-mobile-component/lib/components/tabBar'),
    Button: require('mk-mobile-component/lib/components/button'),
    Calendar: require('mk-mobile-component/lib/components/calendar'),
    Checkbox: require('mk-mobile-component/lib/components/checkbox'),
    DatePicker: require('mk-mobile-component/lib/components/datePicker'),
    DatePickerView: require('mk-mobile-component/lib/components/datePickerView'),
    ImagePicker: require('mk-mobile-component/lib/components/imagePicker'),
    InputItem: require('mk-mobile-component/lib/components/inputItem'),
    PickerView: require('mk-mobile-component/lib/components/pickerView'),
    Picker: require('mk-mobile-component/lib/components/picker'),
    Range: require('mk-mobile-component/lib/components/range'),
    Radio: require('mk-mobile-component/lib/components/radio'),
    Switch: require('mk-mobile-component/lib/components/switch'),
    SearchBar: require('mk-mobile-component/lib/components/searchBar'),
    Slider: require('mk-mobile-component/lib/components/slider'),
    Stepper: require('mk-mobile-component/lib/components/stepper'),
    TextareaItem: require('mk-mobile-component/lib/components/textareaItem'),
    Accordion: require('mk-mobile-component/lib/components/accordion'),
    Badge: require('mk-mobile-component/lib/components/badge'),
    Carousel: require('mk-mobile-component/lib/components/carousel'),
    Card: require('mk-mobile-component/lib/components/card'),
    Grid: require('mk-mobile-component/lib/components/grid'),
    Icon: require('mk-mobile-component/lib/components/icon'),
    List: require('mk-mobile-component/lib/components/list'),
    Steps: require('mk-mobile-component/lib/components/steps'),
    Tag: require('mk-mobile-component/lib/components/tag'),
    ActionSheet: require('mk-mobile-component/lib/components/actionSheet'),
    ActivityIndicator: require('mk-mobile-component/lib/components/activityIndicator'),
    Progress: require('mk-mobile-component/lib/components/progress'),
    PullToRefresh: require('mk-mobile-component/lib/components/pullToRefresh'),
    SwipeAction: require('mk-mobile-component/lib/components/swipeAction'),
    ListView: require('mk-mobile-component/lib/components/listView'),
    Result: require('mk-mobile-component/lib/components/result'),

    Modal: require('mk-mobile-component/lib/components/modal'),
    Toast: require('mk-mobile-component/lib/components/toast'),
    NoticeBar: require('mk-mobile-component/lib/components/noticeBar'),
    LocaleWrapper: require('mk-mobile-component/lib/components/localeWrapper'),
}


